#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_border                off
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       stack
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10


# mission-control desktop labels
yabai -m space 1 --label 1
yabai -m space --create
yabai -m space 2 --label 2
yabai -m space --create
yabai -m space 3 --label 3
yabai -m space --create
yabai -m space 4 --label 4


yabai -m rule --add app=Kitty space=1
yabai -m rule --add app=Chrome space=1
yabai -m rule --add app=Music space=2
yabai -m rule --add app=Slack space=3
yabai -m rule --add app=Discord space=3
yabai -m rule --add app=draw.io space=4

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

echo "yabai configuration loaded.."
