# 'brew install'
# GNU find utils
# GNU grep
# GNU sed
# GNU utils
brew "bat"
brew "coreutils"
brew "fd"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "git-extras"
brew "gnu-sed"
brew "grep"
brew "htop"
brew "jq"
brew "node"
brew "python"
brew "ripgrep"
brew "ssh-copy-id"
brew "stow"
brew "tree-sitter-cli"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
